const pics = [
    'url("/tamadi_ain_barCouncil/1.png")',
    'url("/tamadi_ain_barCouncil/2.png")',
    'url("/tamadi_ain_barCouncil/3.png")',
    'url("/tamadi_ain_barCouncil/4.png")',
    'url("/tamadi_ain_barCouncil/5.png")',
    'url("/tamadi_ain_barCouncil/6.png")',
    'url("/tamadi_ain_barCouncil/7.png")',
    'url("/tamadi_ain_barCouncil/8.png")',
    'url("/tamadi_ain_barCouncil/9.png")',
    'url("/tamadi_ain_barCouncil/10.png")',
    'url("/tamadi_ain_barCouncil/11.png")',
    'url("/tamadi_ain_barCouncil/12.png")',
    'url("/tamadi_ain_barCouncil/13.png")',
    'url("/tamadi_ain_barCouncil/14.png")',
    'url("/tamadi_ain_barCouncil/15.png")',
    'url("/tamadi_ain_barCouncil/16.png")',
    'url("/tamadi_ain_barCouncil/17.png")',
    'url("/tamadi_ain_barCouncil/18.png")',
    'url("/tamadi_ain_barCouncil/19.png")',
    'url("/tamadi_ain_barCouncil/20.png")',
    'url("/tamadi_ain_barCouncil/21.png")',
    'url("/tamadi_ain_barCouncil/22.png")',
    'url("/tamadi_ain_barCouncil/23.png")',
    'url("/tamadi_ain_barCouncil/24.png")',
    'url("/tamadi_ain_barCouncil/25.png")',
    'url("/tamadi_ain_barCouncil/26.png")',
    'url("/tamadi_ain_barCouncil/27.png")',
    'url("/tamadi_ain_barCouncil/28.png")',
    'url("/tamadi_ain_barCouncil/29.png")',
    'url("/tamadi_ain_barCouncil/30.png")',
    'url("/tamadi_ain_barCouncil/31.png")',
    'url("/tamadi_ain_barCouncil/32.png")',
    'url("/tamadi_ain_barCouncil/33.png")',
    'url("/tamadi_ain_barCouncil/34.png")',
    'url("/tamadi_ain_barCouncil/35.png")',
    'url("/tamadi_ain_barCouncil/36.png")',
    'url("/tamadi_ain_barCouncil/37.png")',
    'url("/tamadi_ain_barCouncil/38.png")',
    'url("/tamadi_ain_barCouncil/39.png")',
    'url("/tamadi_ain_barCouncil/40.png")',
    'url("/tamadi_ain_barCouncil/41.png")',
    'url("/tamadi_ain_barCouncil/42.png")',
    'url("/tamadi_ain_barCouncil/43.png")',
    'url("/tamadi_ain_barCouncil/44.png")',
    'url("/tamadi_ain_barCouncil/45.png")',
    'url("/tamadi_ain_barCouncil/46.png")',
    'url("/tamadi_ain_barCouncil/47.png")',
    'url("/tamadi_ain_barCouncil/48.png")',
    'url("/tamadi_ain_barCouncil/49.png")',
    'url("/tamadi_ain_barCouncil/50.png")',
    'url("/tamadi_ain_barCouncil/51.png")',
    'url("/tamadi_ain_barCouncil/52.png")',
    'url("/tamadi_ain_barCouncil/53.png")',
    'url("/tamadi_ain_barCouncil/54.png")',
    'url("/tamadi_ain_barCouncil/55.png")',
    'url("/tamadi_ain_barCouncil/56.png")',
    'url("/tamadi_ain_barCouncil/57.png")',
    'url("/tamadi_ain_barCouncil/58.png")',
    'url("/tamadi_ain_barCouncil/59.png")',
    'url("/tamadi_ain_barCouncil/60.png")',
    'url("/tamadi_ain_barCouncil/61.png")',
    'url("/tamadi_ain_barCouncil/62.png")',
    'url("/tamadi_ain_barCouncil/63.png")',
    'url("/tamadi_ain_barCouncil/64.png")',
    'url("/tamadi_ain_barCouncil/65.png")',
    'url("/tamadi_ain_barCouncil/66.png")',
    'url("/tamadi_ain_barCouncil/67.png")',
    'url("/tamadi_ain_barCouncil/68.png")',
    'url("/tamadi_ain_barCouncil/69.png")',
    'url("/tamadi_ain_barCouncil/70.png")',
    'url("/tamadi_ain_barCouncil/71.png")',
    'url("/tamadi_ain_barCouncil/72.png")',
    'url("/tamadi_ain_barCouncil/73.png")',
    'url("/tamadi_ain_barCouncil/74.png")',
    'url("/tamadi_ain_barCouncil/75.png")',
    'url("/tamadi_ain_barCouncil/76.png")',
    'url("/tamadi_ain_barCouncil/77.png")',
    'url("/tamadi_ain_barCouncil/78.png")',
    'url("/tamadi_ain_barCouncil/79.png")',
    'url("/tamadi_ain_barCouncil/80.png")',
    'url("/tamadi_ain_barCouncil/81.png")',
    'url("/tamadi_ain_barCouncil/82.png")',
    'url("/tamadi_ain_barCouncil/83.png")',
    'url("/tamadi_ain_barCouncil/84.png")',
    'url("/tamadi_ain_barCouncil/85.png")',
    'url("/tamadi_ain_barCouncil/86.png")',
    'url("/tamadi_ain_barCouncil/87.png")',
    'url("/tamadi_ain_barCouncil/88.png")',
    'url("/tamadi_ain_barCouncil/89.png")',
    'url("/tamadi_ain_barCouncil/90.png")',
    'url("/tamadi_ain_barCouncil/91.png")',
    'url("/tamadi_ain_barCouncil/92.png")',
    'url("/tamadi_ain_barCouncil/93.png")',
    'url("/tamadi_ain_barCouncil/94.png")',
    'url("/tamadi_ain_barCouncil/95.png")',
    'url("/tamadi_ain_barCouncil/96.png")',
    'url("/tamadi_ain_barCouncil/97.png")',
    'url("/tamadi_ain_barCouncil/98.png")',
    'url("/tamadi_ain_barCouncil/99.png")',
    
 
]


const pic = document.querySelector("section")
function showImage(){
    var a = Math.floor(Math.random()* pics.length)
    var img = pics[a]
    console.log(img)
    pic.style.backgroundImage = img
    pic.style.img = img
}